apiVersion: v1
kind: Pod
metadata:
  name: tomcat-server
spec:
  containers:
    - name: tomcat-server
      image: tomcat
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8000
