apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-outside-cluster
spec:
  ports:
    - port: 9999
      targetPort: 8888
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: httpd-endpoint-slice
  labels:
    kubernetes.io/service-name: httpd-outside-cluster
addressType: IPv4
endpoints:
  - addresses:
      - "10.10.0.171"
      # - "10.10.0.172"
ports:
  - port: 8888
