apiVersion: v1
kind: Pod
metadata:
  name: web-servers
  labels:
    component: backend
    app: server
spec:
  containers:
    - name: tomcat-web-server
      image: tomcat
      ports:
        - containerPort: 8080
