apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  # finalizers:
  #   - "custom/test-finalizers"
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
