apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    name: nginx-server
    app: nginx-replicaset
spec:
  containers:
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
        - name: nginx-replicaset
          image: nginx
          ports:
            - containerPort: 80
