apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx6-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx
          ports:
            - containerPort: 80
