apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-scale
spec:
  selector:
    matchLabels:
      app: nginx-scale
  template:
    metadata:
      labels:
        app: nginx-scale
    spec:
      containers:
        - name: nginx-scale
          image: nginx:1.16.1
          ports:
            - containerPort: 80
