apiVersion: v1
kind: Pod
metadata:
  name: web-server-required-during
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - windows
                  - linux
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server-preferred-during
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 5
          preference:
            matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
        - weight: 6
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - kind-worker2
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
