apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    component: backend
    app: server
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: kind-worker
