apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  # ttlSecondsAfterFinished: 100
  completions: 2
  template:
    spec:
      containers:
        - name: calculation
          image: ruby:3.0-bullseye
          command: ["ruby", "-e", 'puts "2 + 3 = #{2 + 3}"']
      restartPolicy: Never
