# belongs to test namespace
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: test
  labels:
    app: web-server
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: web-server
  ports:
    - port: 80
      targetPort: 80
---
# belongs to default namespace
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
