apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: web-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
# by default apply -f will apply to "default" namespace
# run below command to see different
# kubectl apply -f CONFIG_FILE -n=test
