apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: rails-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: ariefkahfi/hello-rails-app
          ports:
            - containerPort: 3000
