apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: postgres-database
  template:
    metadata:
      labels:
        tier: postgres-database
    spec:
      containers:
        - name: postgres-database
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "123456"
