apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: NodePort
  selector:
    app: rails-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
