apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    tier: postgres-database
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: <Port>
      targetPort: <Target Port>
